window-scale=0.5
hwdec=auto
# scale=ewa_lanczos4sharpest # too tough for laptop
scale=bilinear # ewa_lanczos4sharpest # lanczos is too tough for laptop
save-position-on-quit=yes
save-watch-history=yes
slang=en
fullscreen=yes
border=no
# sub-font-size=33
osd-font-size=33
autofit-larger=75%
sub-delay=1
title=${filename}

# for hdr to work
# vo=gpu-next
# gpu-api=vulkan
# target-colorspace-hint=yes

glsl-shaders="~~/shaders/FSR.glsl"
