# --- Window Settings ---
# window_padding_width 10
window_margin_width 4

tab_bar_style powerline

# --- Font Settings ---
font_size 10.0
font_family JetBrains Mono NL

# --- Scrolling Settings ---
scrollback_lines 100000
shell_integration enabled

term xterm-kitty

enabled_layouts fat:bias=80;full_size=1;mirrored=false,tall:bias=70;full_size=1;mirrored=false

# --- Keyboard Bindings ---
# Kitty copies and pastes with Ctrl+Shift+C/V by default. Explicitly defined here:
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

map ctrl+shift+w new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+n new_os_window_with_cwd

map ctrl+shift+] next_tab
map ctrl+tab next_tab
map ctrl+shift+[ prev_tab
map ctrl+shift+tab prev_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# Navigate between windows
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# vim-kitty-navigator support
allow_remote_control yes
listen_on unix:@mykitty
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

# Resize windows
map alt+h resize_window narrower 2
map alt+l resize_window wider 2
map alt+k resize_window taller 2
map alt+j resize_window shorter 2

map ctrl+] next_window
map ctrl+[ prev_window

# Unbinding or passing raw characters to shell:
# map ctrl+- no_op
# map ctrl+= no_op
map ctrl+shift+t no_op
map ctrl+shift+q no_op
map ctrl+shift+f10 no_op
map ctrl+shift+f11 no_op

# Dank color generation
include dank-tabs.conf
include dank-theme.conf

